import { createSVGRect, createSVGText, createSVGPath, showTooltip, hideTooltip } from './utils.js';

let svg;
let redoFillBar;
let particles = [];
let archPaths = {};

export function initArchitectureSVG(containerId) {
    const container = document.getElementById(containerId);
    svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttribute('viewBox', '0 0 1400 750');
    svg.setAttribute('width', '100%');
    svg.setAttribute('height', '100%');
    
    // Static Connections (Arrows)
    svg.appendChild(createSVGPath('M 150,200 L 230,200', '#334155', 2, '5,5')); // User to PGA
    svg.appendChild(createSVGPath('M 370,200 L 450,200', '#334155', 2, '5,5')); // PGA to SGA
    
    // Foreground Processes
    drawProcess(90, 200, 'User', '#6366f1', 'Foreground User Session / Application', false);
    drawProcess(200, 200, 'Server', '#8b5cf6', 'Dedicated Server Process', false);
    
    // PGA Subcomponents
    const pgaGroup = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    pgaGroup.appendChild(createSVGRect(250, 100, 140, 200, 8, 'rgba(245, 158, 11, 0.05)', '#f59e0b', 2));
    pgaGroup.appendChild(createSVGText(320, 120, 'PGA', '#fcd34d', 16, 'middle', 'bold'));
    svg.appendChild(pgaGroup);
    
    drawSubComponent(260, 130, 120, 35, 'PGA_SQL', 'SQL Work Areas', '#f59e0b', 'Sort Area, Hash Area, Bitmap Merge Area.');
    drawSubComponent(260, 175, 120, 35, 'PGA_Sess', 'Session Memory', '#f59e0b', 'Logon information, package variables.');
    drawSubComponent(260, 220, 120, 35, 'PGA_Cursor', 'Private SQL', '#f59e0b', 'Cursor state, execution areas.');
    
    // SGA Base Container
    const sgaGroup = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    sgaGroup.id = 'arch_SGA';
    sgaGroup.appendChild(createSVGRect(430, 50, 930, 360, 12, 'rgba(59, 130, 246, 0.05)', '#3b82f6', 2));
    sgaGroup.appendChild(createSVGText(895, 40, 'System Global Area (SGA)', '#93c5fd', 18, 'middle', 'bold'));
    svg.appendChild(sgaGroup);
    
    // SGA Subcomponents (Top Row)
    const spGroup = drawComponent(450, 70, 280, 110, 'SharedPool', 'Shared Pool', '#3b82f6', 'Caches various constructs that can be shared among users.');
    spGroup.appendChild(createSVGText(590, 115, '[Lib Cache, Dict Cache, Result Cache]', '#bfdbfe', 11, 'middle', 'normal'));
    
    drawComponent(750, 70, 130, 110, 'LargePool', 'Large Pool', '#6366f1', 'UGA, I/O buffers for RMAN/Parallel.');
    drawComponent(900, 70, 130, 110, 'JavaPool', 'Java Pool', '#8b5cf6', 'Memory for JVM.');
    drawComponent(1050, 70, 130, 110, 'Streams', 'Streams Pool', '#a855f7', 'Oracle Streams & GoldenGate.');
    drawComponent(1200, 70, 130, 110, 'FixedSGA', 'Fixed SGA', '#64748b', 'Internal state information, locks, latches.');
    
    // SGA Subcomponents (Middle Row)
    const bcGroup = drawComponent(450, 200, 430, 110, 'BufferCache', 'Database Buffer Cache', '#10b981', 'Caches data blocks read from disk. DBWn writes dirty buffers.');
    bcGroup.appendChild(createSVGText(665, 245, '[Default Pool, Keep Pool, Recycle Pool]', '#a7f3d0', 11, 'middle', 'normal'));
    
    const imGroup = drawComponent(900, 200, 430, 110, 'InMemory', 'In-Memory Area', '#ec4899', 'IM column store for extreme analytics.');
    imGroup.appendChild(createSVGText(1115, 245, '[IMCU - Column Units, SMU - Metadata]', '#fbcfe8', 11, 'middle', 'normal'));
    
    // Redo Log Buffer with Fill Bar
    const redoGrp = drawComponent(450, 330, 880, 60, 'RedoBuffer', 'Redo Log Buffer', '#ef4444', 'Circular buffer holding redo entries generated by DML.');
    redoFillBar = createSVGRect(450, 330, 0, 60, 8, 'rgba(239, 68, 68, 0.6)', 'none', 0);
    redoGrp.insertBefore(redoFillBar, redoGrp.childNodes[1]); 
    
    // Lines from Background processes to disks
    svg.appendChild(createSVGPath('M 700,530 L 700,600', '#10b981', 2, '5,5')); // DBWn to DataFiles
    svg.appendChild(createSVGPath('M 800,530 L 850,600', '#ef4444', 2, '5,5')); // LGWR to Redo
    svg.appendChild(createSVGPath('M 900,530 L 715,600', '#f59e0b', 2, '5,5')); // CKPT to Control
    svg.appendChild(createSVGPath('M 1000,530 L 1025,600', '#0ea5e9', 2, '5,5')); // ARCn to Archive
    
    // Background Processes (11 Processes)
    const procs = [
        {id: 'PMON', x: 300}, {id: 'SMON', x: 400}, {id: 'RECO', x: 500}, {id: 'LREG', x: 600},
        {id: 'DBWn', x: 700, color: '#10b981'}, {id: 'LGWR', x: 800, color: '#ef4444'}, 
        {id: 'CKPT', x: 900, color: '#f59e0b'}, {id: 'ARCn', x: 1000, color: '#0ea5e9'}, 
        {id: 'MMON', x: 1100}, {id: 'MMNL', x: 1200}, {id: 'CJQ0', x: 1300}
    ];
    procs.forEach(p => drawProcess(p.x, 490, p.id, p.color || '#94a3b8', `Background Process: ${p.id}`, true));
    
    // Physical Disks / Files
    drawDisk(250, 600, 'SPFILE', 'SPFILE', '#cbd5e1', 'Server Parameter File.');
    drawDisk(400, 600, 'PwdFile', 'Password File', '#cbd5e1', 'SYSDBA Authentication.');
    drawDisk(550, 600, 'DataFiles', 'Data Files', '#10b981', 'Physical storage of database blocks.');
    drawDisk(700, 600, 'ControlFiles', 'Control Files', '#f59e0b', 'Metadata, Checkpoint SCNs, database structure.');
    drawDisk(850, 600, 'OnlineRedo', 'Online Redo Logs', '#ef4444', 'Multiplexed redo logs for instance recovery.');
    drawDisk(1000, 600, 'ArchiveLogs', 'Archived Redo', '#0ea5e9', 'Offline copies of filled online redo logs.');
    drawDisk(1150, 600, 'Flashback', 'Flashback Logs', '#d946ef', 'Before-image blocks for Flashback Database.');
    
    // Particle paths
    archPaths = {
        'parse': { x1: 200, y1: 200, x2: 590, y2: 120, color: '#93c5fd' },
        'readDisk': { x1: 600, y1: 600, x2: 665, y2: 250, color: '#34d399' },
        'fetch': { x1: 665, y1: 250, x2: 200, y2: 200, color: '#34d399' },
        'redoGen': { x1: 200, y1: 200, x2: 890, y2: 360, color: '#fca5a5' },
        'dbwWrite': { x1: 665, y1: 250, x2: 600, y2: 600, color: '#34d399' },
        'lgwrWrite': { x1: 890, y1: 360, x2: 900, y2: 600, color: '#fca5a5' },
        'ckptToControl': { x1: 900, y1: 490, x2: 750, y2: 600, color: '#fcd34d' }
    };

    container.appendChild(svg);
    requestAnimationFrame(renderArchParticles);
}

function drawComponent(x, y, w, h, id, title, color, desc) {
    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    g.id = `arch_${id}`;
    g.style.cursor = 'pointer';
    
    const rect = createSVGRect(x, y, w, h, 8, 'rgba(15, 23, 42, 0.85)', color, 2);
    const text = createSVGText(x + w/2, y + 30, title, '#fff', 15);
    
    g.appendChild(rect); g.appendChild(text);
    g.addEventListener('mouseenter', (e) => showTooltip(e, title, desc));
    g.addEventListener('mouseleave', hideTooltip);
    svg.appendChild(g);
    return g;
}

function drawSubComponent(x, y, w, h, id, title, color, desc) {
    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    g.id = `arch_${id}`;
    g.style.cursor = 'pointer';
    
    const rect = createSVGRect(x, y, w, h, 4, 'rgba(15, 23, 42, 0.95)', color, 1);
    const text = createSVGText(x + w/2, y + 22, title, '#fff', 11, 'middle', 'normal');
    
    g.appendChild(rect); g.appendChild(text);
    g.addEventListener('mouseenter', (e) => showTooltip(e, title, desc));
    g.addEventListener('mouseleave', hideTooltip);
    svg.appendChild(g);
    return g;
}

function drawProcess(x, y, title, color, desc, isBg) {
    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    g.id = `proc_${title}`;
    g.style.cursor = 'pointer';
    
    const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
    circle.setAttribute('cx', x); circle.setAttribute('cy', y);
    circle.setAttribute('r', isBg ? 30 : 38);
    circle.setAttribute('fill', 'rgba(15,23,42,0.95)');
    circle.setAttribute('stroke', color);
    circle.setAttribute('stroke-width', 2);
    
    const text = createSVGText(x, y + 5, title, '#fff', isBg ? 12 : 15);
    
    g.appendChild(circle); g.appendChild(text);
    g.addEventListener('mouseenter', (e) => showTooltip(e, title, desc));
    g.addEventListener('mouseleave', hideTooltip);
    svg.appendChild(g);
}

function drawDisk(x, y, id, title, color, desc) {
    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    g.id = `disk_${id}`;
    g.style.cursor = 'pointer';
    
    const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    path.setAttribute('d', `M${x},${y+20} A60,15 0 0,0 ${x+120},${y+20} L${x+120},${y+90} A60,15 0 0,1 ${x},${y+90} Z`);
    path.setAttribute('fill', 'rgba(15,23,42,0.9)');
    path.setAttribute('stroke', color);
    path.setAttribute('stroke-width', 2);
    
    const top = document.createElementNS('http://www.w3.org/2000/svg', 'ellipse');
    top.setAttribute('cx', x+60); top.setAttribute('cy', y+20);
    top.setAttribute('rx', 60); top.setAttribute('ry', 15);
    top.setAttribute('fill', 'rgba(15,23,42,0.9)');
    top.setAttribute('stroke', color);
    top.setAttribute('stroke-width', 2);
    
    const text = createSVGText(x + 60, y + 60, title, '#fff', 13);
    
    g.appendChild(path); g.appendChild(top); g.appendChild(text);
    g.addEventListener('mouseenter', (e) => showTooltip(e, title, desc));
    g.addEventListener('mouseleave', hideTooltip);
    svg.appendChild(g);
}

export function updateArchitecture(state) {
    const fillPercent = Math.min(state.redoBufferLevel / 100, 1);
    redoFillBar.setAttribute('width', 880 * fillPercent);
    if(fillPercent > 0.8) {
        redoFillBar.setAttribute('fill', 'rgba(239, 68, 68, 0.9)');
    } else {
        redoFillBar.setAttribute('fill', 'rgba(239, 68, 68, 0.6)');
    }
}

export function animateComponentGlow(targetId, type) {
    const el = document.getElementById(targetId);
    if(el) {
        el.classList.add(`glow-${type === 'write' ? 'red' : 'green'}`);
        setTimeout(() => el.classList.remove(`glow-${type === 'write' ? 'red' : 'green'}`), 800);
    }
}

export function shootArchParticle(pathName, duration = 600) {
    const pInfo = archPaths[pathName];
    if(!pInfo) return;
    
    const particle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
    particle.setAttribute('r', 8);
    particle.setAttribute('fill', pInfo.color);
    particle.setAttribute('filter', `drop-shadow(0 0 10px ${pInfo.color})`);
    svg.appendChild(particle);
    
    particles.push({
        el: particle, startX: pInfo.x1, startY: pInfo.y1, endX: pInfo.x2, endY: pInfo.y2,
        startTime: performance.now(), duration: duration, progress: 0
    });
}

function renderArchParticles(time) {
    particles = particles.filter(p => {
        p.progress = (time - p.startTime) / p.duration;
        if(p.progress >= 1) {
            if(p.el.parentNode) svg.removeChild(p.el);
            return false;
        }
        const ease = 1 - Math.pow(1 - p.progress, 3); // Cubic ease out
        const currX = p.startX + (p.endX - p.startX) * ease;
        const currY = p.startY + (p.endY - p.startY) * ease;
        
        p.el.setAttribute('cx', currX);
        p.el.setAttribute('cy', currY);
        return true;
    });
    requestAnimationFrame(renderArchParticles);
}
