import { createSVGRect, createSVGText, createSVGPath, showTooltip, hideTooltip } from './utils.js';

let svg;
let redoFillBar;
let particles = [];
let archPaths = {};

export function initArchitectureSVG(containerId) {
    const container = document.getElementById(containerId);
    svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttribute('viewBox', '0 0 1200 650');
    svg.setAttribute('width', '100%');
    svg.setAttribute('height', '100%');
    
    // Static Connections (Arrows)
    svg.appendChild(createSVGPath('M 120,200 L 220,200', '#334155', 2, '5,5')); // User to PGA
    svg.appendChild(createSVGPath('M 320,200 L 400,200', '#334155', 2, '5,5')); // PGA to SGA
    
    // Server Process & PGA
    drawProcess(100, 200, 'User', '#6366f1', 'Foreground User Session', false);
    drawComponent(200, 160, 120, 80, 'PGA', 'PGA', '#f59e0b', 'Program Global Area: SQL Work Areas, Sort Area, Hash Area.');
    
    // SGA Base Container
    const sgaGroup = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    sgaGroup.id = 'arch_SGA';
    sgaGroup.appendChild(createSVGRect(380, 50, 750, 360, 12, 'rgba(59, 130, 246, 0.05)', '#3b82f6', 2));
    sgaGroup.appendChild(createSVGText(755, 40, 'System Global Area (SGA)', '#93c5fd', 18, 'middle', 'bold'));
    svg.appendChild(sgaGroup);
    
    // SGA Subcomponents
    drawComponent(400, 70, 260, 100, 'SharedPool', 'Shared Pool', '#3b82f6', 'Library Cache (Parsed SQL), Data Dictionary Cache.');
    drawComponent(680, 70, 150, 100, 'LargePool', 'Large Pool', '#6366f1', 'UGA, I/O buffers for RMAN/Parallel.');
    drawComponent(850, 70, 120, 100, 'JavaPool', 'Java Pool', '#8b5cf6', 'Memory for JVM.');
    drawComponent(990, 70, 120, 100, 'Streams', 'Streams Pool', '#a855f7', 'Oracle Streams & GoldenGate.');
    
    drawComponent(400, 190, 430, 120, 'BufferCache', 'Database Buffer Cache', '#10b981', 'Caches data blocks read from disk. DBWn writes dirty buffers.');
    drawComponent(850, 190, 260, 120, 'InMemory', 'In-Memory Area', '#ec4899', 'IM column store - IMCU, SMU, IMEU.');
    
    // Redo Log Buffer with Fill Bar
    const redoGrp = drawComponent(400, 330, 710, 60, 'RedoBuffer', 'Redo Log Buffer', '#ef4444', 'Circular buffer holding redo entries generated by DML.');
    redoFillBar = createSVGRect(400, 330, 0, 60, 8, 'rgba(239, 68, 68, 0.6)', 'none', 0);
    redoGrp.insertBefore(redoFillBar, redoGrp.childNodes[1]); 
    
    // Lines from Background processes to disks
    svg.appendChild(createSVGPath('M 620,500 L 620,560', '#10b981', 2, '5,5')); // DBWn to DataFiles
    svg.appendChild(createSVGPath('M 720,500 L 775,560', '#ef4444', 2, '5,5')); // LGWR to Redo
    svg.appendChild(createSVGPath('M 820,500 L 615,560', '#f59e0b', 2, '5,5')); // CKPT to Control
    svg.appendChild(createSVGPath('M 920,500 L 935,560', '#0ea5e9', 2, '5,5')); // ARCn to Archive
    
    // Background Processes
    const procs = [
        {id: 'PMON', x: 420}, {id: 'SMON', x: 520}, {id: 'DBWn', x: 620, color: '#10b981'},
        {id: 'LGWR', x: 720, color: '#ef4444'}, {id: 'CKPT', x: 820, color: '#f59e0b'},
        {id: 'ARCn', x: 920, color: '#0ea5e9'}, {id: 'MMON', x: 1020}, {id: 'RECO', x: 1100}
    ];
    procs.forEach(p => drawProcess(p.x, 470, p.id, p.color || '#64748b', `Background Process: ${p.id}`, true));
    
    // Physical Disks
    drawDisk(400, 560, 'DataFiles', 'Data Files', '#10b981', 'Physical storage of database blocks.');
    drawDisk(560, 560, 'ControlFiles', 'Control Files', '#f59e0b', 'Metadata, Checkpoint SCNs, database structure.');
    drawDisk(720, 560, 'OnlineRedo', 'Online Redo Logs', '#ef4444', 'Multiplexed redo logs for instance recovery.');
    drawDisk(880, 560, 'ArchiveLogs', 'Archived Redo', '#0ea5e9', 'Offline copies of filled online redo logs.');
    
    // Particle paths
    archPaths = {
        'parse': { x1: 100, y1: 200, x2: 530, y2: 120, color: '#93c5fd' },
        'readDisk': { x1: 450, y1: 560, x2: 615, y2: 250, color: '#34d399' },
        'fetch': { x1: 615, y1: 250, x2: 100, y2: 200, color: '#34d399' },
        'redoGen': { x1: 100, y1: 200, x2: 755, y2: 360, color: '#fca5a5' },
        'dbwWrite': { x1: 615, y1: 250, x2: 455, y2: 560, color: '#34d399' },
        'lgwrWrite': { x1: 755, y1: 360, x2: 775, y2: 560, color: '#fca5a5' },
        'ckptToControl': { x1: 820, y1: 470, x2: 615, y2: 560, color: '#fcd34d' }
    };

    container.appendChild(svg);
    requestAnimationFrame(renderArchParticles);
}

function drawComponent(x, y, w, h, id, title, color, desc) {
    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    g.id = `arch_${id}`;
    g.style.cursor = 'pointer';
    
    const rect = createSVGRect(x, y, w, h, 8, 'rgba(15, 23, 42, 0.85)', color, 2);
    const text = createSVGText(x + w/2, y + h/2 + 5, title, '#fff', 15);
    
    g.appendChild(rect); g.appendChild(text);
    g.addEventListener('mouseenter', (e) => showTooltip(e, title, desc));
    g.addEventListener('mouseleave', hideTooltip);
    svg.appendChild(g);
    return g;
}

function drawProcess(x, y, title, color, desc, isBg) {
    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    g.id = `proc_${title}`;
    g.style.cursor = 'pointer';
    
    const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
    circle.setAttribute('cx', x); circle.setAttribute('cy', y);
    circle.setAttribute('r', isBg ? 28 : 38);
    circle.setAttribute('fill', 'rgba(15,23,42,0.95)');
    circle.setAttribute('stroke', color);
    circle.setAttribute('stroke-width', 2);
    
    const text = createSVGText(x, y + 5, title, '#fff', isBg ? 13 : 15);
    
    g.appendChild(circle); g.appendChild(text);
    g.addEventListener('mouseenter', (e) => showTooltip(e, title, desc));
    g.addEventListener('mouseleave', hideTooltip);
    svg.appendChild(g);
}

function drawDisk(x, y, id, title, color, desc) {
    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    g.id = `disk_${id}`;
    g.style.cursor = 'pointer';
    
    const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    path.setAttribute('d', `M${x},${y+20} A55,15 0 0,0 ${x+110},${y+20} L${x+110},${y+90} A55,15 0 0,1 ${x},${y+90} Z`);
    path.setAttribute('fill', 'rgba(15,23,42,0.9)');
    path.setAttribute('stroke', color);
    path.setAttribute('stroke-width', 2);
    
    const top = document.createElementNS('http://www.w3.org/2000/svg', 'ellipse');
    top.setAttribute('cx', x+55); top.setAttribute('cy', y+20);
    top.setAttribute('rx', 55); top.setAttribute('ry', 15);
    top.setAttribute('fill', 'rgba(15,23,42,0.9)');
    top.setAttribute('stroke', color);
    top.setAttribute('stroke-width', 2);
    
    const text = createSVGText(x + 55, y + 60, title, '#fff', 13);
    
    g.appendChild(path); g.appendChild(top); g.appendChild(text);
    g.addEventListener('mouseenter', (e) => showTooltip(e, title, desc));
    g.addEventListener('mouseleave', hideTooltip);
    svg.appendChild(g);
}

export function updateArchitecture(state) {
    const fillPercent = Math.min(state.redoBufferLevel / 100, 1);
    redoFillBar.setAttribute('width', 710 * fillPercent);
    if(fillPercent > 0.8) {
        redoFillBar.setAttribute('fill', 'rgba(239, 68, 68, 0.9)');
    } else {
        redoFillBar.setAttribute('fill', 'rgba(239, 68, 68, 0.6)');
    }
}

export function animateComponentGlow(targetId, type) {
    const el = document.getElementById(targetId);
    if(el) {
        el.classList.add(`glow-${type === 'write' ? 'red' : 'green'}`);
        setTimeout(() => el.classList.remove(`glow-${type === 'write' ? 'red' : 'green'}`), 800);
    }
}

export function shootArchParticle(pathName, duration = 600) {
    const pInfo = archPaths[pathName];
    if(!pInfo) return;
    
    const particle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
    particle.setAttribute('r', 6);
    particle.setAttribute('fill', pInfo.color);
    particle.setAttribute('filter', `drop-shadow(0 0 8px ${pInfo.color})`);
    svg.appendChild(particle);
    
    particles.push({
        el: particle, startX: pInfo.x1, startY: pInfo.y1, endX: pInfo.x2, endY: pInfo.y2,
        startTime: performance.now(), duration: duration, progress: 0
    });
}

function renderArchParticles(time) {
    particles = particles.filter(p => {
        p.progress = (time - p.startTime) / p.duration;
        if(p.progress >= 1) {
            if(p.el.parentNode) svg.removeChild(p.el);
            return false;
        }
        const ease = 1 - Math.pow(1 - p.progress, 3);
        const currX = p.startX + (p.endX - p.startX) * ease;
        const currY = p.startY + (p.endY - p.startY) * ease;
        
        p.el.setAttribute('cx', currX);
        p.el.setAttribute('cy', currY);
        return true;
    });
    requestAnimationFrame(renderArchParticles);
}
